{"name": "test_3", "status": "skipped", "statusDetails": {"message": "XFAIL 这是个待修复bug\n\nAssertionError: assert 3 == 4", "trace": "@pytest.mark.xfail(reason=\"这是个待修复bug\")\n    def test_3():\n        a = 3\n        b = 4\n>       assert a == b\nE       assert 3 == 4\n\ntestcases\\test_study.py:111: AssertionError"}, "start": 1675225351693, "stop": 1675225351693, "uuid": "acb0aef0-7133-4159-95d7-2ea4987f22b1", "historyId": "f1592601590cd602bb5696608cb4a23c", "testCaseId": "90ab251d1201646462a91d9cde900166", "fullName": "testcases.test_study#test_3", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='这是个待修复bug')"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_study"}, {"name": "host", "value": "LAPTOP-AKAH6LMA"}, {"name": "thread", "value": "11320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_study"}]}